services:
  blog:
    image: ghcr.io/patryk-bernasiewicz/blog-astro:190525_0141
    ports:
      - target: 3660
        published: 3660
        protocol: tcp
        mode: host
    restart: unless-stopped
