name: Deploy to VPS via Docker Context

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

      - name: Add VPS host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.VPS_PORT }} -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Set up Docker Context for VPS
        run: |
          docker context create vps --docker "host=ssh://${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_PORT }}"
          docker context use vps
          echo "Verifying Docker context connection..."
          docker --context vps ps # This command will attempt to list containers on the remote host

      - name: Deploy with Docker Compose on VPS
        run: |
          docker compose -f compose.prod.yml up -d --build

      - name: Remove Docker context
        if: always()
        run: docker context rm vps
