name: Deploy to VPS via Docker Context

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      CONTENTFUL_DELIVERY_TOKEN: ${{ secrets.CONTENTFUL_DELIVERY_TOKEN }}
    steps:
      - name: Set Docker image tag
        run: |
          echo "DATE=$(date +'%d%m%y_%H%M')" >> $GITHUB_ENV

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install --reporter=silent --frozen-lockfile

      - name: Build static site
        run: pnpm build --silent

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.DATE }}

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.VPS_KEYSCAN_ARGS }} >> ~/.ssh/known_hosts

      - name: Create docker context with SSH
        uses: arwynfr/actions-docker-context@v2
        with:
          docker_host: "${{ secrets.VPS_SSH_CONNECTION_STRING }}"
          context_name: "prod-server"
          ssh_key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          use_context: true

      - name: Deploy blog via docker context
        run: IMAGE_TAG=${{ env.DATE }} docker stack deploy --with-registry-auth -c compose.prod.yml blog-astro
